---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(knitr)
library(timeDate)
library(xlsx)
library(XML)
library(data.table)

setwd("c:/HW/ReproResearch/data")
stepdata <- read.table("activity.csv", sep=",",header=TRUE)
head(stepdata)

StepTrans <- data.frame(steps=as.numeric(stepdata$steps),date=as.Date(stepdata$date), interval=stepdata$interval)
sum(is.na(StepTrans$steps))
sum(is.na(StepTrans$date))
sum(is.na(StepTrans$interval))
```


## What is mean total number of steps taken per day?


```{r}
good <- complete.cases(StepTrans)

compcases <- StepTrans[good, ]

steps.day <- aggregate(steps ~ date, data=compcases, FUN=sum)
hist(steps.day$steps)
mean(steps.day$steps)
median(steps.day$steps)
```



## What is the average daily activity pattern?

What is the average daily activity pattern?
```{r}
steps.interval <- aggregate(steps ~ interval, data= compcases, FUN=mean)
plot(steps ~  interval, steps.interval, type = "l")
maxInt <- max(steps.interval$steps)
StepMaxInt <- subset(steps.interval,steps.interval$steps==maxInt)
StepMaxInt 
```



## Imputing missing values

Imputing missing values
```{r}
### missing values
totalObs <- length(StepTrans$steps) 
## Number of observations missing in dataset
colSums(is.na(StepTrans))

AvgStepsInt <- mean(compcases$steps)
head(AvgStepsInt)
```


## Are there differences in activity patterns between weekdays and weekends?
```{r}
ImputedSteps <- data.frame(steps=ifelse(is.na(StepTrans$steps), AvgStepsInt, StepTrans$steps),date=StepTrans$date, interval=StepTrans$interval)
Imp.steps.day <- aggregate(steps ~ date, data=ImputedSteps, FUN=sum)
hist(Imp.steps.day$steps)
mean(Imp.steps.day$steps)
median(Imp.steps.day$steps)

## The date is being misread
Imp.steps.interval <- aggregate(steps ~ interval + date, data=ImputedSteps, FUN=sum)

##work from here
v <- c("Monday","Tuesday", "Wednesday", "Thursday", "Friday")
Imp.steps.interval$Day <- ifelse(weekdays(Imp.steps.interval$date) %in% v,  "Weekday", "Weekend")
Imp.steps.interval$Day <- as.factor(Imp.steps.interval$Day)

WE.steps.interval <- subset(Imp.steps.interval, Imp.steps.interval$Day =="Weekend")
WE.Aggregate <- aggregate(steps ~  interval, data= WE.steps.interval, FUN=mean)


WD.steps.interval <- subset(Imp.steps.interval, Imp.steps.interval$Day =="Weekday")
WD.Aggregate <- aggregate(steps ~  interval, data= WD.steps.interval, FUN=mean)
opt  = par(mfrow= c(2,1))
plot(steps ~  interval, WE.Aggregate, type = "l", main="Weekends")
plot(steps ~  interval, WD.Aggregate, type = "l", main="Weekdays")
par(opt)
```
